project:
  type: website

website:
  title: "FAS1002_projet-final"
  description: | 
    "Page d'accueil du travail final pour le cours FAS1002 -
    Initiation √† la programmation en sciences sociales √†
    l'Universit√© de Montr√©al donn√© lors du trimestre A2022."

  reader-mode: true
# URL de votre site une fois publi√© - <VOTREUSERNAME> √† changer 
  site-url: https://PhilRosa.github.io/FAS1002_projet-final/
# URL de votre r√©pertoire - VOTREUSERNAME/VOTRE-R√âPERTOIRE √† changer
  repo-url: https://github.com/PhilRosa/FAS1002_projet-final/
  repo-actions: [edit, issue, source]
  
# Options √† changer pour le menu ou la barre de navigation
  navbar:
    background: primary
    logo: /assets/img/FAS1002.png 	# Logo image to be displayed left of the title.
    logo-alt: Logo du cours FAS1002
    # Alternate text for the logo image.
    search: true
    # menu
    left:
      - href: index.qmd
        text: Page d'accueil
      - href: intro.qmd
        text: Introduction
      - href: import.qmd
        text: Banque de donn√©es
      - exploration.qmd
    right:
      - href: a-propos.qmd
        text: Page √† droite 

# footer
  page-footer:
    left: |
      [Propuls√© par des logiciels libres üíñ](https://github.com/FAS1002/A22){.nav-link}
    center:
    # Changer VOTRE NOM pour ce que vous voulez
      - text: "Philippe Rosa"
        href: mailto:philippe.rosa@umontreal.ca
      - text: "Bertrand Turcotte"
        href: mailto:bertrand.turcotte@umontreal.ca
    right:
      - icon: github
        href: https://github.com/FAS1002/
        aria-label: GitHub du cours FAS1002
        

# set favicon
  favicon: /assets/img/FAS1002.png
format:
  html:
    theme: yeti
    code-fold: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github
    toc: true
    lang: "fr"
    smooth-scroll: true

execute:
  freeze: auto
  
editor: visual
